# Generated by Django 3.2.8 on 2021-10-29 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('task_id', models.UUIDField(default=uuid.uuid4)),
                ('address', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('locations', models.ManyToManyField(to='geocoding.Location')),
            ],
        ),
    ]
