# Generated by Django 3.2.8 on 2021-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='task',
            new_name='task_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
