# Generated by Django 3.2.8 on 2021-10-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoding.task'),
        ),
    ]
