# Generated by Django 3.2.8 on 2021-10-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0002_auto_20211029_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='geocoding.task'),
        ),
    ]
