# Generated by Django 3.2.8 on 2021-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0002_alter_link_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
