# Generated by Django 3.2.8 on 2021-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(True, 'done'), (False, 'running')], default=False),
        ),
    ]
