# Generated by Django 3.2.8 on 2021-10-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='task',
            new_name='task_id',
        ),
    ]
