# Generated by Django 3.2.8 on 2021-10-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0008_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_point', to='geocoding.task'),
        ),
    ]
