# Generated by Django 3.2.8 on 2021-10-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0009_alter_point_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_link', to='geocoding.task'),
        ),
    ]
