# Generated by Django 3.2.8 on 2021-10-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0010_alter_link_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='geocoding.task'),
        ),
        migrations.AlterField(
            model_name='point',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='geocoding.task'),
        ),
    ]
